name = "HydrodynamicStability"
uuid = "7863843b-5d10-4cf2-b9e5-ac583df0c545"
authors = ["DislikePinapple <sheng_y@tju.edu.cn> and contributors"]
version = "0.1.3"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
Aqua = "0.8"
ForwardDiff = "0.10"
LinearAlgebra = "1.9"
JuliaFormatter = "1.0"
Pkg = "1.9"
Printf = "1.9"
RecipesBase = "1.3"
SafeTestsets = "0.1"
SpecialFunctions = "2.3"
Test = "1.0"
UnPack = "1.0"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = [
    "Pkg",
    "SafeTestsets",
    "Test",
    "Aqua",
    "SpecialFunctions",
    "JuliaFormatter",
]
